const scienceQuestions971_1000 = [
  {id:971, category:"science", difficulty:4, question:"What is the chemical symbol for gold?", options:["Au","Ag","Gd","Go"], answer:"Au"},
  {id:972, category:"science", difficulty:4, question:"Which planet is known as the Red Planet?", options:["Mars","Venus","Jupiter","Saturn"], answer:"Mars"},
  {id:973, category:"science", difficulty:4, question:"What gas do plants absorb from the atmosphere?", options:["Carbon Dioxide","Oxygen","Nitrogen","Hydrogen"], answer:"Carbon Dioxide"},
  {id:974, category:"science", difficulty:4, question:"Which organelle is known as the powerhouse of the cell?", options:["Mitochondria","Nucleus","Ribosome","Chloroplast"], answer:"Mitochondria"},
  {id:975, category:"science", difficulty:4, question:"Which element has the atomic number 1?", options:["Hydrogen","Helium","Oxygen","Carbon"], answer:"Hydrogen"},
  {id:976, category:"science", difficulty:4, question:"What is the largest planet in our solar system?", options:["Jupiter","Saturn","Neptune","Earth"], answer:"Jupiter"},
  {id:977, category:"science", difficulty:4, question:"Which scientist proposed the theory of relativity?", options:["Albert Einstein","Isaac Newton","Galileo Galilei","Nikola Tesla"], answer:"Albert Einstein"},
  {id:978, category:"science", difficulty:4, question:"Which blood cells carry oxygen?", options:["Red Blood Cells","White Blood Cells","Platelets","Plasma"], answer:"Red Blood Cells"},
  {id:979, category:"science", difficulty:4, question:"What is the hardest natural substance on Earth?", options:["Diamond","Graphite","Quartz","Corundum"], answer:"Diamond"},
  {id:980, category:"science", difficulty:4, question:"Which force keeps planets in orbit around the sun?", options:["Gravity","Magnetism","Friction","Tension"], answer:"Gravity"},
  {id:981, category:"science", difficulty:4, question:"What type of energy is stored in a stretched spring?", options:["Potential Energy","Kinetic Energy","Thermal Energy","Chemical Energy"], answer:"Potential Energy"},
  {id:982, category:"science", difficulty:4, question:"Which is the smallest unit of life?", options:["Cell","Atom","Molecule","Organ"], answer:"Cell"},
  {id:983, category:"science", difficulty:4, question:"Which vitamin is produced when skin is exposed to sunlight?", options:["Vitamin D","Vitamin A","Vitamin C","Vitamin K"], answer:"Vitamin D"},
  {id:984, category:"science", difficulty:4, question:"Which planet has a ring system?", options:["Saturn","Mars","Earth","Venus"], answer:"Saturn"},
  {id:985, category:"science", difficulty:4, question:"Which gas is most abundant in the Earth's atmosphere?", options:["Nitrogen","Oxygen","Carbon Dioxide","Argon"], answer:"Nitrogen"},
  {id:986, category:"science", difficulty:4, question:"Which particle has a negative charge?", options:["Electron","Proton","Neutron","Photon"], answer:"Electron"},
  {id:987, category:"science", difficulty:4, question:"Which organ in humans detoxifies chemicals?", options:["Liver","Kidney","Lungs","Pancreas"], answer:"Liver"},
  {id:988, category:"science", difficulty:4, question:"Which branch of science studies living organisms?", options:["Biology","Physics","Chemistry","Geology"], answer:"Biology"},
  {id:989, category:"science", difficulty:4, question:"What is the boiling point of water at sea level?", options:["100°C","90°C","212°C","80°C"], answer:"100°C"},
  {id:990, category:"science", difficulty:4, question:"Which planet is closest to the Sun?", options:["Mercury","Venus","Earth","Mars"], answer:"Mercury"},
  {id:991, category:"science", difficulty:4, question:"Which force causes objects to fall to the ground?", options:["Gravity","Magnetism","Electricity","Friction"], answer:"Gravity"},
  {id:992, category:"science", difficulty:4, question:"Which part of the cell contains genetic material?", options:["Nucleus","Mitochondria","Ribosome","Cytoplasm"], answer:"Nucleus"},
  {id:993, category:"science", difficulty:4, question:"Which planet is known for its Great Red Spot?", options:["Jupiter","Mars","Saturn","Neptune"], answer:"Jupiter"},
  {id:994, category:"science", difficulty:4, question:"Which organ system is responsible for digestion?", options:["Digestive System","Respiratory System","Circulatory System","Nervous System"], answer:"Digestive System"},
  {id:995, category:"science", difficulty:4, question:"Which phenomenon causes rainbows?", options:["Refraction of light","Reflection of sound","Diffraction of water","Absorption of heat"], answer:"Refraction of light"},
  {id:996, category:"science", difficulty:4, question:"Which natural disaster is measured with a Richter scale?", options:["Earthquake","Tsunami","Hurricane","Volcano"], answer:"Earthquake"},
  {id:997, category:"science", difficulty:4, question:"Which gas do humans exhale?", options:["Carbon Dioxide","Oxygen","Nitrogen","Hydrogen"], answer:"Carbon Dioxide"},
  {id:998, category:"science", difficulty:4, question:"Which part of the eye controls the amount of light entering?", options:["Iris","Cornea","Lens","Retina"], answer:"Iris"},
  {id:999, category:"science", difficulty:4, question:"Which planet is known as the 'Blue Planet'?", options:["Earth","Neptune","Uranus","Saturn"], answer:"Earth"},
  {id:1000, category:"science", difficulty:4, question:"Which scientist is known for the laws of motion?", options:["Isaac Newton","Albert Einstein","Galileo Galilei","Nikola Tesla"], answer:"Isaac Newton"}
];
